spring.application.name=SpringSecurity


# Configuraciones de Spring Security
# spring.security.user.name=admin
# spring.security.user.password=123456
# spring.security.user.roles=admin,user


# Configuracion de la Base de Datos
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL_MYSQL_SPRINGSECURITYJWT_DEV}
spring.datasource.username=${DB_USR_MYSQL_SPRINGSECURITYJWT_DEV}
spring.datasource.password=${DB_PWD_MYSQL_SPRINGSECURITYJWT_DEV}


