spring.application.name=SpringSecurity


# Configuraciones de Spring Security
# spring.security.user.name=admin
# spring.security.user.password=123456
# spring.security.user.roles=admin,user



# Configuración de la Base de Datos
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRINGSECURITYJWT_DB_URL_MYSQL_DEV}
spring.datasource.username=${SPRINGSECURITYJWT_DB_USR_MYSQL_DEV}
spring.datasource.password=${SPRINGSECURITYJWT_DB_PWD_MYSQL_DEV}


# Configuracion Seguridad Token JWT
jwt.secret.key=${SPRINGSECURITYJWT_JWT_TOKEN_DEV}
# Expiracion del token en milisegundos. Equivalente a un dia
jwt.expiration.time=86400000


